#include <stdio.h>
#include "square.h" /* generated by rpcgen */
int
main (int argc, char **argv) {
	CLIENT *cl;
	square_in in;
	square_out *outp;
	if (argc != 3) {
		printf("usage: client <hostname> <integer-value>\n");
	exit(1);
	}
	cl = clnt_create(argv[1], SQUARE_PROG, SQUARE_VERS, "tcp");
	in.argl = atol(argv[2]);
	if ((outp = squareproc_1(&in, cl)) == NULL) {
		printf("Client %s error\n", clnt_sperror(cl, argv[1]));
		exit(1);
	}
	printf("result: %ld\n", outp->resl);
	exit(0);
}
